print("bienvenido a gmail")
print("para iniciar sesion ingrese su correo")
correo=input("para iniciar sesion ingrese su correo")
print("contraseña")
contraseña=input()
print("a quien deseas enviar el correo")
correo_receptor=input()
print("asunto")
asunto=input()
print("que mensaje desea escribir")
mensaje=input()
print("cantidad de archivos a enviar")
archivos=int (input())
print ("su correo fue enviado")
